test: &default

  # Credentials for REST APIs
  client_id: AfJuCRANwMA0KXRatBm08NfEJHg9eXDefpYmZIbK3254nj0Ubz6zUFTHyb37
  client_secret: ECZuuBBx0dHctqiXBmf0F6cw7ZYb5Lu5OO-2eiXLUPlvpCLYogCKDZxfYmQ-

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  client_id: ASb29hDqBkJdgo_RT0wnVmNYtLTphq4H0eprkFt60z_bW5EGjRubDLWbYl8W
  client_secret: EO5pqRCru2L-c9JwM8tMwr3t2QqRWaPPxbK9h7qj90QeJp9Ng_5pWzUK1HxQ
  mode: live
