options:
  - name: Number of Country Preferences Allowed
    slug: num_preferences
    class_name: Integer
    default: 10
  - name: Site Title
    slug: site_title
    class_name: String
    default: YMGE
  - name: Long Site Title
    slug: long_site_title
    class_name: String
    default: Yale Model Government Europe 2014
  - name: Public Site URL
    slug: public_site_url
    class_name: String
    default: http://ymge.org
  - name: Registration URL
    slug: registration_url
    class_name: String
    default: http://registration.ymge.org
  - name: Address
    slug: address
    class_name: Text
    default: 'PO Box 203352 <br>New Haven, CT 06520'
  - name: Phone
    slug: phone
    default: +1 (412) 877-1272
    class_name: String
  - name: Check Address
    slug: check_address
    class_name: Text
    default: |
      <strong>Yale Model Government Europe</strong><br>
      &#8453; David Steiner<br>
      P.O. Box 203352<br>
      New Haven, CT 06520
  - name: Copyright
    slug: copyright
    class_name: Text
    default: 'Copyright 2010-2014 Yale Model Government Europe CZ, o.s.'
  - name: Main Email
    slug: main_email
    class_name: String
    default: recruitment@ymge.org
  - name: Technology Email
    slug: tech_email
    class_name: String
    default: technology@ymge.org
  - name: Payment Email
    slug: payment_email
    class_name: String
    default: finance@ymge.org
  - name: Email Sender
    slug: from_email
    class_name: String
    default: info@ymge.org
  - name: Registration Due Date
    slug: registration_due_date
    class_name: Date
    default: '2014-03-31'
  - name: Accept EUR as Payment
    slug: accept_eur
    class_name: Boolean
    default: 1
  - name: Allow Bank Transfer
    slug: allow_bank_transfer
    class_name: Boolean
    default: 1
  - name: Delegate Fee (USD)
    slug: delegate_fee
    class_name: Integer
    default: 40
  - name: Delegation Price
    slug: delegation_price
    class_name: Text
    default: 
  - name: Deposit (EUR)
    slug: deposit_eur
    class_name: Integer
    default: 300
  - name: Deposit (USD)
    slug: deposit_usd
    class_name: Integer
    default: 450
  - name: Maximum Delegates Per Advisor
    slug: max_delegates_per_advisor
    class_name: Integer
    default: 10
  - name: Site-Wide Alert
    slug: alert
    class_name: Text
    default: 
  - name: Privacy Policy
    slug: privacy_policy
    class_name: Text
    default: 
  - name: Favicon URL
    slug: favicon
    class_name: String
    default: 
  - name: Delegate Cap
    slug: delegate_cap
    class_name: Integer
    default: 