options:
  - name: Number of Country Preferences Allowed
    slug: num_preferences
    class_name: Integer
    default: 10
  - name: Site Title
    slug: site_title
    class_name: String
    default: Yale Model Government Europe
  - name: Registration Due Date
    slug: registration_due_date
    class_name: Date
    default: '2014-03-31'
  - name: Delegate Fee (USD)
    slug: delegate_fee
    class_name: Integer
    default: 40
  - name: Delegation Price
    slug: delegation_price
    class_name: Text
    default: 
  - name: Deposit
    slug: deposit
    class_name: Integer
    default: 300
  - name: Maximum Delegates Per Advisor
    slug: max_delegates_per_advisor
    class_name: Integer
    default: 10